### ISSUE TITLE
Question Regarding The Dataset

### ISSUE THREAD

**Issue by huyquangdao** [liuzeming01/DuRecDial#5]
Hi authors. Thank you very much for releasing the dataset.

I have a question. Is there any way to identify who (the seeker or the agent) starts a conversation ?

Looking forward to your response.

**Comment by liuzeming01** [comment]
If the first goal is "Greetings/寒暄", the seeker starts the conversation, otherwise, the user starts the conversation.

**Comment by huyquangdao** [comment]
Indeed. Thank you very much !
